/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWireguardRouteImport } from './routes/_authenticated/wireguard'
import { Route as AuthenticatedVouchersRouteImport } from './routes/_authenticated/vouchers'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSessionsRouteImport } from './routes/_authenticated/sessions'
import { Route as AuthenticatedRouterRouteImport } from './routes/_authenticated/router'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPackagesRouteImport } from './routes/_authenticated/packages'
import { Route as AuthenticatedLoginPagesRouteImport } from './routes/_authenticated/login-pages'
import { Route as AuthenticatedDiagnosticsRouteImport } from './routes/_authenticated/diagnostics'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated/audit-logs'
import { Route as ApiMikrotikVouchersRouteImport } from './routes/api/mikrotik/vouchers'
import { Route as ApiMikrotikStatsRouteImport } from './routes/api/mikrotik/stats'
import { Route as ApiMikrotikPackagesRouteImport } from './routes/api/mikrotik/packages'
import { Route as ApiMikrotikOnlineDevicesRouteImport } from './routes/api/mikrotik/online-devices'
import { Route as ApiMikrotikActiveSessionsRouteImport } from './routes/api/mikrotik/active-sessions'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin/roles'
import { Route as ApiPublicConnectorSyncRouteImport } from './routes/api/public/connector/sync'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWireguardRoute = AuthenticatedWireguardRouteImport.update({
  id: '/wireguard',
  path: '/wireguard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVouchersRoute = AuthenticatedVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionsRoute = AuthenticatedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRouterRoute = AuthenticatedRouterRouteImport.update({
  id: '/router',
  path: '/router',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPackagesRoute = AuthenticatedPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLoginPagesRoute = AuthenticatedLoginPagesRouteImport.update({
  id: '/login-pages',
  path: '/login-pages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnosticsRoute =
  AuthenticatedDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiMikrotikVouchersRoute = ApiMikrotikVouchersRouteImport.update({
  id: '/api/mikrotik/vouchers',
  path: '/api/mikrotik/vouchers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMikrotikStatsRoute = ApiMikrotikStatsRouteImport.update({
  id: '/api/mikrotik/stats',
  path: '/api/mikrotik/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMikrotikPackagesRoute = ApiMikrotikPackagesRouteImport.update({
  id: '/api/mikrotik/packages',
  path: '/api/mikrotik/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMikrotikOnlineDevicesRoute =
  ApiMikrotikOnlineDevicesRouteImport.update({
    id: '/api/mikrotik/online-devices',
    path: '/api/mikrotik/online-devices',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMikrotikActiveSessionsRoute =
  ApiMikrotikActiveSessionsRouteImport.update({
    id: '/api/mikrotik/active-sessions',
    path: '/api/mikrotik/active-sessions',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicConnectorSyncRoute = ApiPublicConnectorSyncRouteImport.update({
  id: '/api/public/connector/sync',
  path: '/api/public/connector/sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/login-pages': typeof AuthenticatedLoginPagesRoute
  '/packages': typeof AuthenticatedPackagesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/router': typeof AuthenticatedRouterRoute
  '/sessions': typeof AuthenticatedSessionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/vouchers': typeof AuthenticatedVouchersRoute
  '/wireguard': typeof AuthenticatedWireguardRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/api/mikrotik/active-sessions': typeof ApiMikrotikActiveSessionsRoute
  '/api/mikrotik/online-devices': typeof ApiMikrotikOnlineDevicesRoute
  '/api/mikrotik/packages': typeof ApiMikrotikPackagesRoute
  '/api/mikrotik/stats': typeof ApiMikrotikStatsRoute
  '/api/mikrotik/vouchers': typeof ApiMikrotikVouchersRoute
  '/api/public/connector/sync': typeof ApiPublicConnectorSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/login-pages': typeof AuthenticatedLoginPagesRoute
  '/packages': typeof AuthenticatedPackagesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/router': typeof AuthenticatedRouterRoute
  '/sessions': typeof AuthenticatedSessionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/vouchers': typeof AuthenticatedVouchersRoute
  '/wireguard': typeof AuthenticatedWireguardRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/api/mikrotik/active-sessions': typeof ApiMikrotikActiveSessionsRoute
  '/api/mikrotik/online-devices': typeof ApiMikrotikOnlineDevicesRoute
  '/api/mikrotik/packages': typeof ApiMikrotikPackagesRoute
  '/api/mikrotik/stats': typeof ApiMikrotikStatsRoute
  '/api/mikrotik/vouchers': typeof ApiMikrotikVouchersRoute
  '/api/public/connector/sync': typeof ApiPublicConnectorSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/_authenticated/login-pages': typeof AuthenticatedLoginPagesRoute
  '/_authenticated/packages': typeof AuthenticatedPackagesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/router': typeof AuthenticatedRouterRoute
  '/_authenticated/sessions': typeof AuthenticatedSessionsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/vouchers': typeof AuthenticatedVouchersRoute
  '/_authenticated/wireguard': typeof AuthenticatedWireguardRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/api/mikrotik/active-sessions': typeof ApiMikrotikActiveSessionsRoute
  '/api/mikrotik/online-devices': typeof ApiMikrotikOnlineDevicesRoute
  '/api/mikrotik/packages': typeof ApiMikrotikPackagesRoute
  '/api/mikrotik/stats': typeof ApiMikrotikStatsRoute
  '/api/mikrotik/vouchers': typeof ApiMikrotikVouchersRoute
  '/api/public/connector/sync': typeof ApiPublicConnectorSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/audit-logs'
    | '/dashboard'
    | '/diagnostics'
    | '/login-pages'
    | '/packages'
    | '/reports'
    | '/router'
    | '/sessions'
    | '/settings'
    | '/staff'
    | '/vouchers'
    | '/wireguard'
    | '/admin/roles'
    | '/api/mikrotik/active-sessions'
    | '/api/mikrotik/online-devices'
    | '/api/mikrotik/packages'
    | '/api/mikrotik/stats'
    | '/api/mikrotik/vouchers'
    | '/api/public/connector/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/audit-logs'
    | '/dashboard'
    | '/diagnostics'
    | '/login-pages'
    | '/packages'
    | '/reports'
    | '/router'
    | '/sessions'
    | '/settings'
    | '/staff'
    | '/vouchers'
    | '/wireguard'
    | '/admin/roles'
    | '/api/mikrotik/active-sessions'
    | '/api/mikrotik/online-devices'
    | '/api/mikrotik/packages'
    | '/api/mikrotik/stats'
    | '/api/mikrotik/vouchers'
    | '/api/public/connector/sync'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/audit-logs'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagnostics'
    | '/_authenticated/login-pages'
    | '/_authenticated/packages'
    | '/_authenticated/reports'
    | '/_authenticated/router'
    | '/_authenticated/sessions'
    | '/_authenticated/settings'
    | '/_authenticated/staff'
    | '/_authenticated/vouchers'
    | '/_authenticated/wireguard'
    | '/_authenticated/admin/roles'
    | '/api/mikrotik/active-sessions'
    | '/api/mikrotik/online-devices'
    | '/api/mikrotik/packages'
    | '/api/mikrotik/stats'
    | '/api/mikrotik/vouchers'
    | '/api/public/connector/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiMikrotikActiveSessionsRoute: typeof ApiMikrotikActiveSessionsRoute
  ApiMikrotikOnlineDevicesRoute: typeof ApiMikrotikOnlineDevicesRoute
  ApiMikrotikPackagesRoute: typeof ApiMikrotikPackagesRoute
  ApiMikrotikStatsRoute: typeof ApiMikrotikStatsRoute
  ApiMikrotikVouchersRoute: typeof ApiMikrotikVouchersRoute
  ApiPublicConnectorSyncRoute: typeof ApiPublicConnectorSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wireguard': {
      id: '/_authenticated/wireguard'
      path: '/wireguard'
      fullPath: '/wireguard'
      preLoaderRoute: typeof AuthenticatedWireguardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vouchers': {
      id: '/_authenticated/vouchers'
      path: '/vouchers'
      fullPath: '/vouchers'
      preLoaderRoute: typeof AuthenticatedVouchersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions': {
      id: '/_authenticated/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/router': {
      id: '/_authenticated/router'
      path: '/router'
      fullPath: '/router'
      preLoaderRoute: typeof AuthenticatedRouterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/packages': {
      id: '/_authenticated/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof AuthenticatedPackagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/login-pages': {
      id: '/_authenticated/login-pages'
      path: '/login-pages'
      fullPath: '/login-pages'
      preLoaderRoute: typeof AuthenticatedLoginPagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostics': {
      id: '/_authenticated/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof AuthenticatedDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/mikrotik/vouchers': {
      id: '/api/mikrotik/vouchers'
      path: '/api/mikrotik/vouchers'
      fullPath: '/api/mikrotik/vouchers'
      preLoaderRoute: typeof ApiMikrotikVouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mikrotik/stats': {
      id: '/api/mikrotik/stats'
      path: '/api/mikrotik/stats'
      fullPath: '/api/mikrotik/stats'
      preLoaderRoute: typeof ApiMikrotikStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mikrotik/packages': {
      id: '/api/mikrotik/packages'
      path: '/api/mikrotik/packages'
      fullPath: '/api/mikrotik/packages'
      preLoaderRoute: typeof ApiMikrotikPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mikrotik/online-devices': {
      id: '/api/mikrotik/online-devices'
      path: '/api/mikrotik/online-devices'
      fullPath: '/api/mikrotik/online-devices'
      preLoaderRoute: typeof ApiMikrotikOnlineDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mikrotik/active-sessions': {
      id: '/api/mikrotik/active-sessions'
      path: '/api/mikrotik/active-sessions'
      fullPath: '/api/mikrotik/active-sessions'
      preLoaderRoute: typeof ApiMikrotikActiveSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/connector/sync': {
      id: '/api/public/connector/sync'
      path: '/api/public/connector/sync'
      fullPath: '/api/public/connector/sync'
      preLoaderRoute: typeof ApiPublicConnectorSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiagnosticsRoute: typeof AuthenticatedDiagnosticsRoute
  AuthenticatedLoginPagesRoute: typeof AuthenticatedLoginPagesRoute
  AuthenticatedPackagesRoute: typeof AuthenticatedPackagesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRouterRoute: typeof AuthenticatedRouterRoute
  AuthenticatedSessionsRoute: typeof AuthenticatedSessionsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedVouchersRoute: typeof AuthenticatedVouchersRoute
  AuthenticatedWireguardRoute: typeof AuthenticatedWireguardRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiagnosticsRoute: AuthenticatedDiagnosticsRoute,
  AuthenticatedLoginPagesRoute: AuthenticatedLoginPagesRoute,
  AuthenticatedPackagesRoute: AuthenticatedPackagesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRouterRoute: AuthenticatedRouterRoute,
  AuthenticatedSessionsRoute: AuthenticatedSessionsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedVouchersRoute: AuthenticatedVouchersRoute,
  AuthenticatedWireguardRoute: AuthenticatedWireguardRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiMikrotikActiveSessionsRoute: ApiMikrotikActiveSessionsRoute,
  ApiMikrotikOnlineDevicesRoute: ApiMikrotikOnlineDevicesRoute,
  ApiMikrotikPackagesRoute: ApiMikrotikPackagesRoute,
  ApiMikrotikStatsRoute: ApiMikrotikStatsRoute,
  ApiMikrotikVouchersRoute: ApiMikrotikVouchersRoute,
  ApiPublicConnectorSyncRoute: ApiPublicConnectorSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
